version: "3"
services:
  # Node
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /app
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    links:
      - postgres
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  # Postgres
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: postgres
    ports:
      - 54322:5432
  # Redis
  redis:
    image: redis
    ports:
      - 6379:6379
